apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: umq4i3z5k-go
  janus-idp.io/tekton: umq4i3z5k-go
  backstage.io/kubernetes-id: umq4i3z5k-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: umq4i3z5k-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
